//Register
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "profile_pic":"https://static.wikia.nocookie.net/penguinsofmadagascar/images/c/cd/King_Julien_profile.png/revision/latest?cb=20151125110328",
    "first_name":"Admin",
    "second_name":"The Great",
    "email":"admin@gmail.com",
    "password":"B91371758@b"
}

###

//Log In

POST http://localhost:4000/users/logIn
Content-Type: application/json

{
    "email":"admin@gmail.com",
    "password":"B91371758@b"
}

###

//Get all Users

GET http://localhost:4000/users/getUsers/1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


###

//Get By Id

GET http://localhost:4000/users/getById
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Get By Email

GET http://localhost:4000/users/getByEmail
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Update User Info
PUT  http://localhost:4000/users/update
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "profile_pic":"picture perfect",
    "first_name":"Brian",
    "second_name":"Gathai",
    "email":"gathai6@email.com"
}

###
//Get Inactive Users

GET http://localhost:4000/users/inactive

###
//Deactivate Account

PUT  http://localhost:4000/users/deactivate
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


############

//Question Routes

###

//post Question
POST http://localhost:4000/questions/post
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "title":"Another Test Question",
    "body":"This is Another Test question?",
    "tags":[
        {"tag":"test"},
        {"tag":"fun"},
        {"tag":"laugh"},
        {"tag":"Jitu"},
        {"tag":"nyeri"}
    ]
}

###

//Get All Questions

GET http://localhost:4000/questions/all/1
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###
//Get Single Question
GET http://localhost:4000/questions/single/4c6a6c69-bdff-46d9-b707-e12c97b37a2d
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


###

//Update question

PUT http://localhost:4000/questions/update/008481c2-4619-4746-be85-121b22d7383b
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "title":"PunStar",
    "body":"This is a test question"
}

###

//Delete question

DELETE  http://localhost:4000/questions/delete/c3ade49b-0841-4fb0-8791-b2a47650a400
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

#####

//Answer Routes

POST http://localhost:4000/answers/post/d4e809c6-cb96-46b6-9fb6-78bb99670183
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "answer":"The test question Works"
}

###

//Get All Answers

GET http://localhost:4000/answers/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Get Single question's answers

GET http://localhost:4000/answers/question/d4e809c6-cb96-46b6-9fb6-78bb99670183
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


###

//Update answer

put http://localhost:4000/answers//update/b96b6eb4-3099-440f-9ced-7f0ad18cf330
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "answer":"I am having a great day thanks for asking, sir"
}


###

//Delete Answer

delete http://localhost:4000/answers//delete/e8f56922-fda4-4127-ae10-ba93f796e0f3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Upvote answer
put http://localhost:4000/answers//upvote/c7249fb3-caa6-4300-baba-2e604a213dd9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Downvote answer
put http://localhost:4000/answers//downvote/c7249fb3-caa6-4300-baba-2e604a213dd9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

###

//Accept answer
put http://localhost:4000/answers//accept/77b56150-5d17-44ba-b45d-93f95162d799
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


####3

//Comments Controllers


###

//Add Comment 

POST http://localhost:4000/comments/add/47f8a7df-28c9-465b-bb45-fd746aa232d9
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "comment":"Its Thursday!!!"
}

###

//Update Comment

PUT http://localhost:4000/comments/update/b70f9728-0ae2-4a80-a8cb-d34599a31190
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ

{
    "comment":"Its not Tuesday!!"
}

###

//Get Answer Comments

GET  http://localhost:4000/comments/get/b70f9728-0ae2-4a80-a8cb-d34599a31190
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


//Get All Comments
###
GET  http://localhost:4000/comments/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ


###

DELETE  http://localhost:4000/comments/delete/3e110384-3589-4dcf-8940-04d6c323101e
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCIsIjhkM2QwNGNkLTU5Y2YtNDIzYy1iYzlmLWExYTBmY2RjNWNiOCJdLCJmaXJzdF9uYW1lIjoiTWFzdGVyIiwic2Vjb25kX25hbWUiOiJHYXRoYWkiLCJlbWFpbCI6ImdhdGhhaTIxM0BnbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODc2MjYzNDl9.ykHWfIWcGj83u7lKMZNfaRSImOv9q9pOTV_h3105oyQ