//Register
POST http://localhost:4000/users/register
Content-Type: application/json

{
    "profile_pic":"picture",
    "first_name":"Test",
    "second_name":"User",
    "email":"dee@user.com",
    "password":"B91371758@b"
}
###

//Log In

POST http://localhost:4000/users/logIn
Content-Type: application/json

{
    "email":"dee@user.com",
    "password":"B91371758@b"
}
###

//Get all Users

GET http://localhost:4000/users/getUsers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NTA5M30.Dmfx5rU-UfPAjAR0qnbADQJEbd_4gOoZJdNFY658n14


###

//Get By Id

GET http://localhost:4000/users/getById
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NTA5M30.Dmfx5rU-UfPAjAR0qnbADQJEbd_4gOoZJdNFY658n14

###

//Get By Email

GET http://localhost:4000/users/getByEmail
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NTA5M30.Dmfx5rU-UfPAjAR0qnbADQJEbd_4gOoZJdNFY658n14

###

//Update User Info
PUT  http://localhost:4000/users/update
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NTA5M30.Dmfx5rU-UfPAjAR0qnbADQJEbd_4gOoZJdNFY658n14

{
    "profile_pic":"picture perfect",
    "first_name":"Brian",
    "second_name":"Gathai",
    "email":"gathai6@email.com"
}

###
//Get Inactive Users

GET http://localhost:4000/users/inactive

###
//Deactivate Account

PUT  http://localhost:4000/users/deactivate
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjc5MjYxMDdkLWIxMGQtNDUzMS04OGMwLWIxMWExNTJjMjFlYiIsIjc5MjYxMDdkLWIxMGQtNDUzMS04OGMwLWIxMWExNTJjMjFlYiJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoiZGVlQHVzZXIuY29tIiwicm9sZV9pZCI6WzIsMl0sInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjg3MzQ4MjEyfQ.E4jH_V3k3hfv8abWRWgVl_Kl3qfpOM0S6iadmLw6zds


############

//Question Routes

###

//post Question
POST http://localhost:4000/questions/post
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

{
    "title":"Pundemic",
    "body":"Why did You get fired from the calender company?",
    "tags":[
        {"tag":"greetings"},
        {"tag":"vibes"},
        {"tag":"puns"},
        {"tag":"Dad jokes"},
        {"tag":"laughs"}
    ]
}

###

//Get All Questions

GET http://localhost:4000/questions/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

###
//Get Single Question
GET http://localhost:4000/questions/single/c3ade49b-0841-4fb0-8791-b2a47650a400
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI2MTI3OCwiZXhwIjoxNjg3MjY0ODc4fQ.D9KY_FxP53GDiNACsz6ktnQFg83ofVXMLHLWYoNANwM


###

//Update question

PUT http://localhost:4000/questions/update/18441734-c506-47f5-8389-87a6c4ed11af
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI1MzI2OSwiZXhwIjoxNjg3MjU2ODY5fQ.tiD61b8_5BM0YDSEIPdwgXVi0gQktCajSaTUXt_ssPM

{
    "title":"PunStar",
    "body":"Why did you get fired from the calender company??"
}

###

//Delete question

DELETE  http://localhost:4000/questions/delete/c3ade49b-0841-4fb0-8791-b2a47650a400
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI2MTI3OCwiZXhwIjoxNjg3MjY0ODc4fQ.D9KY_FxP53GDiNACsz6ktnQFg83ofVXMLHLWYoNANwM

#####

//Answer Routes

POST http://localhost:4000/answers/post/0cec4a4d-eba9-471d-a157-89ed24c57ea5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

{
    "answer":"Because I tok a day off"
}

###

//Get All Answers

GET http://localhost:4000/answers/all
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

###

//Get Single question's answers

GET http://localhost:4000/answers/question/c3ade49b-0841-4fb0-8791-b2a47650a400
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI0OTYzOSwiZXhwIjoxNjg3MjUzMjM5fQ.i45GTFhAOQI4lsbuBJJVXKEFe3NbxF9Vcefun0dMejw


###

//Update answer

put http://localhost:4000/answers//update/b96b6eb4-3099-440f-9ced-7f0ad18cf330
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiIsIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMkBlbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODcyMzMzODAsImV4cCI6MTY4NzIzNjk4MH0.Ulow670ZWrMqwFl5EVoiEt6wj4_AOApOT2bxPB_IVdw

{
    "answer":"I am having a great day thanks for asking, sir"
}


###

//Delete Answer

delete http://localhost:4000/answers//delete/e8f56922-fda4-4127-ae10-ba93f796e0f3
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiIsIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMkBlbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODcyMzMzODAsImV4cCI6MTY4NzIzNjk4MH0.Ulow670ZWrMqwFl5EVoiEt6wj4_AOApOT2bxPB_IVdw

###

//Upvote answer
put http://localhost:4000/answers//upvote/d514522d-8dad-4f54-a8b1-a00097ababe0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiIsIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMkBlbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODcyMzMzODAsImV4cCI6MTY4NzIzNjk4MH0.Ulow670ZWrMqwFl5EVoiEt6wj4_AOApOT2bxPB_IVdw

###

//Downvote answer
put http://localhost:4000/answers//downvote/d514522d-8dad-4f54-a8b1-a00097ababe0
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiIsIjExZDIyMzY5LTA5NDctNDAwZC04ZmM2LTFmNDI4MDkyMmJiMiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMkBlbWFpbC5jb20iLCJyb2xlX2lkIjpbMiwyXSwicm9sZSI6InVzZXIiLCJpYXQiOjE2ODcyMzMzODAsImV4cCI6MTY4NzIzNjk4MH0.Ulow670ZWrMqwFl5EVoiEt6wj4_AOApOT2bxPB_IVdw

###

//Accept answer
put http://localhost:4000/answers//accept/3e110384-3589-4dcf-8940-04d6c323101e
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI0OTYzOSwiZXhwIjoxNjg3MjUzMjM5fQ.i45GTFhAOQI4lsbuBJJVXKEFe3NbxF9Vcefun0dMejw


####3

//Comments Controllers


###

//Add Comment 

POST http://localhost:4000/comments/add/b70f9728-0ae2-4a80-a8cb-d34599a31190
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

{
    "comment":"Its Tuesday!!"
}

###

//Update Comment

PUT http://localhost:4000/comments/update/b70f9728-0ae2-4a80-a8cb-d34599a31190
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA

{
    "comment":"Its not Tuesday!!"
}

###

//Get Answer Comments

GET  http://localhost:4000/comments/get/b70f9728-0ae2-4a80-a8cb-d34599a31190
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSIsIjA1YTM1MDRkLWQ0YzUtNGE2Ni04ZGVhLWMyZjRkMjU3OTdlYSJdLCJmaXJzdF9uYW1lIjoiVGVzdCIsInNlY29uZF9uYW1lIjoiVXNlciIsImVtYWlsIjoidGVzdEB1c2VyLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzM0NzYyN30.YnOQIc9p-B_KT8qyYqr25bHuc6pdzQpVCAn4i-z59jA


###

DELETE  http://localhost:4000/comments/delete/3e110384-3589-4dcf-8940-04d6c323101e
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpbImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiIsImZjOWFhMzVmLTNhYzEtNDU3Yy1hOTNhLWE2YjU2NjRhNzg0ZiJdLCJmaXJzdF9uYW1lIjoiS2FyaXVraSIsInNlY29uZF9uYW1lIjoiR2F0aGFpIiwiZW1haWwiOiJnYXRoYWkxMjM0QGVtYWlsLmNvbSIsInJvbGVfaWQiOlsyLDJdLCJyb2xlIjoidXNlciIsImlhdCI6MTY4NzI0OTYzOSwiZXhwIjoxNjg3MjUzMjM5fQ.i45GTFhAOQI4lsbuBJJVXKEFe3NbxF9Vcefun0dMejw

{
    "comment":"Its Tuesday!!"
}